export const mock = [{ id: crypto.randomUUID(), category: "pizza", name: "Маргарита", prices: [399, 599, 799], url: "src/assets/pizza.svg", description: "Классическая итальянская пицца с томатным соусом, моцареллой и базиликом", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Пепперони", prices: [499, 699, 899], url: "src/assets/pizza.svg", description: "Пикантная пицца с пепперони, моцареллой и томатным соусом", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Четыре сыра", prices: [549, 749, 949], url: "src/assets/pizza.svg", description: "Моцарелла, пармезан, горгонзола и рикотта", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Гавайская", prices: [479, 679, 879], url: "src/assets/pizza.svg", description: "Ветчина, ананасы и сыр моцарелла", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Мясная", prices: [599, 799, 999], url: "src/assets/pizza.svg", description: "Колбаса, бекон, ветчина и соус BBQ", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Вегетарианская", prices: [459, 659, 859], url: "src/assets/pizza.svg", description: "Овощи, грибы, томаты и сыр", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Барбекю", prices: [529, 729, 929], url: "src/assets/pizza.svg", description: "Курица, соус BBQ, лук и сыр", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Морская", prices: [629, 829, 1029], url: "src/assets/pizza.svg", description: "Креветки, кальмары, мидии и чесночный соус", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Острая мексиканская", prices: [549, 749, 949], url: "src/assets/pizza.svg", description: "Халапеньо, фарш, перец чили и соус", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Карбонара", prices: [519, 719, 919], url: "src/assets/pizza.svg", description: "Бекон, сливочный соус, сыр и яйцо", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Прошутто", prices: [569, 769, 969], url: "src/assets/pizza.svg", description: "Ветчина прошутто, руккола и пармезан", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Чизбургер пицца", prices: [599, 799, 999], url: "src/assets/pizza.svg", description: "Говядина, сыр, огурцы и соус", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Трюфельная", prices: [699, 899, 1099], url: "src/assets/pizza.svg", description: "Трюфельный соус, грибы и сыр", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Салями", prices: [499, 699, 899], url: "src/assets/pizza.svg", description: "Салями, сыр и томатный соус", isOn: true },
  { id: crypto.randomUUID(), category: "pizza", name: "Курица и грибы", prices: [519, 719, 919], url: "src/assets/pizza.svg", description: "Курица, шампиньоны и сливочный соус", isOn: true },

  { id: crypto.randomUUID(), category: "combo", name: "Комбо №1", prices: [799], url: "src/assets/combo.jpg", description: "Пицца + напиток", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Комбо №2", prices: [899], url: "src/assets/combo.jpg", description: "2 пиццы + напиток", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Комбо для двоих", prices: [1199, 1399], url: "src/assets/combo.jpg", description: "2 пиццы + 2 напитка", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Семейное комбо", prices: [1499, 1699], url: "src/assets/combo.jpg", description: "3 пиццы + напитки", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Ланч комбо", prices: [599], url: "src/assets/combo.jpg", description: "Мини пицца + напиток", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Студенческое", prices: [699], url: "src/assets/combo.jpg", description: "Пицца + напиток", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Вечернее комбо", prices: [999, 1199], url: "src/assets/combo.jpg", description: "Пицца + закуски", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Комбо с десертом", prices: [1099], url: "src/assets/combo.jpg", description: "Пицца + десерт + напиток", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Офисное", prices: [899], url: "src/assets/combo.jpg", description: "Пицца на команду", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Френдс комбо", prices: [1299, 1499], url: "src/assets/combo.jpg", description: "3 пиццы + напитки", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Геймерское", prices: [799], url: "src/assets/combo.jpg", description: "Пицца + закуски", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Премиум комбо", prices: [1599, 1799], url: "src/assets/combo.jpg", description: "Премиум пиццы + напитки", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Мини комбо", prices: [499], url: "src/assets/combo.jpg", description: "Мини пицца + напиток", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Двойное удовольствие", prices: [999], url: "src/assets/combo.jpg", description: "2 пиццы", isOn: true },
  { id: crypto.randomUUID(), category: "combo", name: "Комбо XXL", prices: [1799, 1999], url: "src/assets/combo.jpg", description: "3 большие пиццы + напитки", isOn: true },

  { id: crypto.randomUUID(), category: "drink", name: "Кола", prices: [99], url: "src/assets/drink.jpg", description: "Газированный напиток", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Фанта", prices: [99], url: "src/assets/drink.jpg", description: "Апельсиновый напиток", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Спрайт", prices: [99], url: "src/assets/drink.jpg", description: "Лимонный напиток", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Вода", prices: [59], url: "src/assets/drink.jpg", description: "Минеральная вода", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Сок яблочный", prices: [129, 159], url: "src/assets/drink.jpg", description: "Натуральный сок", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Сок апельсиновый", prices: [129], url: "src/assets/drink.jpg", description: "Свежий сок", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Чай", prices: [89], url: "src/assets/drink.jpg", description: "Горячий чай", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Кофе", prices: [119, 149], url: "src/assets/drink.jpg", description: "Ароматный кофе", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Лимонад", prices: [109], url: "src/assets/drink.jpg", description: "Освежающий напиток", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Энергетик", prices: [149, 179], url: "src/assets/drink.jpg", description: "Энергетический напиток", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Молочный коктейль", prices: [159], url: "src/assets/drink.jpg", description: "Сладкий коктейль", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Капучино", prices: [149], url: "src/assets/drink.jpg", description: "Кофейный напиток", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Латте", prices: [159, 189], url: "src/assets/drink.jpg", description: "Мягкий кофе", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Тоник", prices: [119], url: "src/assets/drink.jpg", description: "Горьковатый напиток", isOn: true },
  { id: crypto.randomUUID(), category: "drink", name: "Морс", prices: [99], url: "src/assets/drink.jpg", description: "Ягодный напиток", isOn: true },

  { id: crypto.randomUUID(), category: "dessert", name: "Чизкейк", prices: [199, 249], url: "src/assets/dessert.jpg", description: "Нежный чизкейк", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Тирамису", prices: [229], url: "src/assets/dessert.jpg", description: "Итальянский десерт", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Мороженое", prices: [99], url: "src/assets/dessert.jpg", description: "Сливочное мороженое", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Брауни", prices: [149], url: "src/assets/dessert.jpg", description: "Шоколадный десерт", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Панкейк", prices: [179, 219], url: "src/assets/dessert.jpg", description: "Сладкие панкейки", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Маффин", prices: [119], url: "src/assets/dessert.jpg", description: "Кекс с начинкой", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Пирожное", prices: [129], url: "src/assets/dessert.jpg", description: "Сладкое пирожное", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Штрудель", prices: [199, 239], url: "src/assets/dessert.jpg", description: "Яблочный десерт", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Эклер", prices: [139], url: "src/assets/dessert.jpg", description: "Заварное пирожное", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Профитроли", prices: [159, 189], url: "src/assets/dessert.jpg", description: "Маленькие пирожные", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Сырники", prices: [149], url: "src/assets/dessert.jpg", description: "Творожные сырники", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Пудинг", prices: [129], url: "src/assets/dessert.jpg", description: "Нежный десерт", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Фруктовый салат", prices: [139], url: "src/assets/dessert.jpg", description: "Свежие фрукты", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Шоколадный торт", prices: [249, 299], url: "src/assets/dessert.jpg", description: "Торт с шоколадом", isOn: true },
  { id: crypto.randomUUID(), category: "dessert", name: "Круассан", prices: [99], url: "src/assets/dessert.jpg", description: "Слоёная выпечка", isOn: true },

  { id: crypto.randomUUID(), category: "snack", name: "Картофель фри", prices: [149], url: "src/assets/snack.jpg", description: "Хрустящий картофель", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Наггетсы", prices: [179, 229], url: "src/assets/snack.jpg", description: "Куриные наггетсы", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Крылышки", prices: [199], url: "src/assets/snack.jpg", description: "Острые куриные крылья", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Луковые кольца", prices: [139], url: "src/assets/snack.jpg", description: "Жареные кольца", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Сырные палочки", prices: [169, 219], url: "src/assets/snack.jpg", description: "Сыр в панировке", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Чесночный хлеб", prices: [129], url: "src/assets/snack.jpg", description: "Хрустящий хлеб", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Начос", prices: [159], url: "src/assets/snack.jpg", description: "Чипсы с соусом", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Хот-дог", prices: [179], url: "src/assets/snack.jpg", description: "Сосиска в булке", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Бургер мини", prices: [199, 249], url: "src/assets/snack.jpg", description: "Мини бургер", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Сэндвич", prices: [169], url: "src/assets/snack.jpg", description: "Бутерброд с начинкой", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Попкорн", prices: [99], url: "src/assets/snack.jpg", description: "Солёный попкорн", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Креветки в кляре", prices: [229, 279], url: "src/assets/snack.jpg", description: "Жареные креветки", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Сырные шарики", prices: [159], url: "src/assets/snack.jpg", description: "Фритюрный сыр", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Пельмени жареные", prices: [199], url: "src/assets/snack.jpg", description: "Хрустящие пельмени", isOn: true },
  { id: crypto.randomUUID(), category: "snack", name: "Кесадилья", prices: [229], url: "src/assets/snack.jpg", description: "Мексиканская закуска", isOn: true },
];